### ISSUE TITLE
Implement RegexQueries

### ISSUE THREAD

**Issue by steveshortt** [SynapseProject/handlers.DataTransformation.net#2]
Iimplement this directly in Handler? (no need to outsource to zephyr).

```yaml
      RegexQueries:
      - Expression: ^\w+[\w-\.]*\@\w+((-\w+)|(\w*))\.[a-z]{2,3}$
        ExecuteLineByLine: true
        PreserveOutputAsIs: true
```
