### ISSUE TITLE
Implement JsonQueries

### ISSUE THREAD

**Issue by steveshortt** [SynapseProject/handlers.DataTransformation.net#3]
- Wraps the Zephyr JsonHelpers `public static object Select(string json, string expression)` method
- This needs to convert non-JSON input to JSON before query, then optionally convert it back `PreserveOutputAsIs: true|false`.  Follow the same basic pattern as using XSLT transformation.

```yaml
      JsonQueries:
      - Expression: $..Products[?(@.Price >= 50)].Name
        PreserveOutputAsIs: true
      - Expression: $.Manufacturers[?(@.Name == 'Acme Co')]
```
